// Code generated by testdata/gnu/record.py from real GNU bash and coreutils; DO NOT EDIT BY HAND.
// Source: GNU bash 5.2.37(1)-release printf builtin, bash on Linux/amd64 (host debby).
// Each script ran as `bash -c` in an empty temporary directory with LC_ALL=C
// unless locale says otherwise; stdout, stderr and the exit status are what
// GNU bash + coreutils produced.

package gobash

var printfGNUCases = []struct {
	name       string
	script     string
	locale     string
	want       string
	wantStderr string
	wantExit   int
}{
	{name: "format octal utf8 e acute", script: `printf '\303\251'`, locale: "C", want: "\xc3\xa9", wantStderr: "", wantExit: 0},
	{name: "format octal letters", script: `printf '\101\102\103'`, locale: "C", want: "ABC", wantStderr: "", wantExit: 0},
	{name: "format octal one digit", script: `printf '\1|\7|\0|'`, locale: "C", want: "\x01|\x07|\x00|", wantStderr: "", wantExit: 0},
	{name: "format octal two digits", script: `printf '\12\41'`, locale: "C", want: "\n!", wantStderr: "", wantExit: 0},
	{name: "format octal stops after three digits", script: `printf '\1011'`, locale: "C", want: "A1", wantStderr: "", wantExit: 0},
	{name: "format octal leading zero takes three digits", script: `printf '\0101'`, locale: "C", want: "\x081", wantStderr: "", wantExit: 0},
	{name: "format octal zero then escape", script: `printf '\0\0377A'`, locale: "C", want: "\x00\x1f7A", wantStderr: "", wantExit: 0},
	{name: "format octal overflow wraps", script: `printf '\400|\777|\477'`, locale: "C", want: "\x00|\xff|?", wantStderr: "", wantExit: 0},
	{name: "format octal high bytes", script: `printf '\200\377\376'`, locale: "C", want: "\x80\xff\xfe", wantStderr: "", wantExit: 0},
	{name: "format octal stops at 8", script: `printf '\18|\8|\9'`, locale: "C", want: "\x018|\\8|\\9", wantStderr: "", wantExit: 0},
	{name: "format nul between text", script: `printf 'a\0b'`, locale: "C", want: "a\x00b", wantStderr: "", wantExit: 0},
	{name: "format hex", script: `printf '\x41\x61\x7e'`, locale: "C", want: "Aa~", wantStderr: "", wantExit: 0},
	{name: "format hex one digit", script: `printf '\x4|\xa|'`, locale: "C", want: "\x04|\n|", wantStderr: "", wantExit: 0},
	{name: "format hex stops after two digits", script: `printf '\x414'`, locale: "C", want: "A4", wantStderr: "", wantExit: 0},
	{name: "format hex upper and lower digits", script: `printf '\xFF\xfe\xAb'`, locale: "C", want: "\xff\xfe\xab", wantStderr: "", wantExit: 0},
	{name: "format hex missing digit", script: `printf 'a\xg'`, locale: "C", want: "a\\xg", wantStderr: "bash: line 1: printf: missing hex digit for \\x\n", wantExit: 0},
	{name: "format hex at end", script: `printf 'a\x'`, locale: "C", want: "a\\x", wantStderr: "bash: line 1: printf: missing hex digit for \\x\n", wantExit: 0},
	{name: "format unicode ascii", script: `printf '\u0041\u7e\U00000042'`, locale: "C", want: "A~B", wantStderr: "", wantExit: 0},
	{name: "format unicode stops after four digits", script: `printf '\u00411'`, locale: "C", want: "A1", wantStderr: "", wantExit: 0},
	{name: "format unicode short", script: `printf '\u41|\U43|'`, locale: "C", want: "A|C|", wantStderr: "", wantExit: 0},
	{name: "format unicode nul", script: `printf 'a\u0000b'`, locale: "C", want: "a\x00b", wantStderr: "", wantExit: 0},
	{name: "format unicode missing digit", script: `printf 'a\uzz'`, locale: "C", want: "a\\uzz", wantStderr: "bash: line 1: printf: missing unicode digit for \\u\n", wantExit: 0},
	{name: "format unicode upper missing digit", script: `printf 'a\U'`, locale: "C", want: "a\\U", wantStderr: "bash: line 1: printf: missing unicode digit for \\U\n", wantExit: 0},
	{name: "format unicode e acute utf8", script: `printf '\u00e9'`, locale: "C.UTF-8", want: "\xc3\xa9", wantStderr: "", wantExit: 0},
	{name: "format unicode euro utf8", script: `printf '\u20ac|\u20AC'`, locale: "C.UTF-8", want: "\xe2\x82\xac|\xe2\x82\xac", wantStderr: "", wantExit: 0},
	{name: "format unicode astral utf8", script: `printf '\U0001F600'`, locale: "C.UTF-8", want: "\xf0\x9f\x98\x80", wantStderr: "", wantExit: 0},
	{name: "format unicode two byte boundary utf8", script: `printf '\u0080\u07ff\u0800'`, locale: "C.UTF-8", want: "\xc2\x80\xdf\xbf\xe0\xa0\x80", wantStderr: "", wantExit: 0},
	{name: "format unicode stops after eight digits utf8", script: `printf '\U0001F6001'`, locale: "C.UTF-8", want: "\xf0\x9f\x98\x801", wantStderr: "", wantExit: 0},
	{name: "format unicode surrogate utf8", script: `printf '\uD800|\uDFFF'`, locale: "C.UTF-8", want: "\xed\xa0\x80|\xed\xbf\xbf", wantStderr: "", wantExit: 0},
	{name: "format unicode beyond max utf8", script: `printf '\U00110000|\U001FFFFF|\U03FFFFFF'`, locale: "C.UTF-8", want: "\xf4\x90\x80\x80|\xf7\xbf\xbf\xbf|\xfb\xbf\xbf\xbf\xbf", wantStderr: "", wantExit: 0},
	{name: "format unicode 31 bit utf8", script: `printf '\U7FFFFFFF|\U80000000|\UFFFFFFFF|'`, locale: "C.UTF-8", want: "\xfd\xbf\xbf\xbf\xbf\xbf|||", wantStderr: "", wantExit: 0},
	{name: "format unicode max utf8", script: `printf '\U0010FFFF|\uFFFF'`, locale: "C.UTF-8", want: "\xf4\x8f\xbf\xbf|\xef\xbf\xbf", wantStderr: "", wantExit: 0},
	{name: "format simple escapes", script: `printf '\a\b\e\E\f\n\r\t\v'`, locale: "C", want: "\x07\x08\x1b\x1b\x0c\n\x0d\t\x0b", wantStderr: "", wantExit: 0},
	{name: "format backslash and quotes", script: `printf '\\|\"|\?|'"'"'\'"'"''`, locale: "C", want: "\\|\"|?|''", wantStderr: "", wantExit: 0},
	{name: "format unknown escapes pass through", script: `printf '\q\z\c\%%'`, locale: "C", want: "\\q\\z\\c\\%", wantStderr: "", wantExit: 0},
	{name: "format trailing backslash", script: `printf 'a\'`, locale: "C", want: "a\\", wantStderr: "", wantExit: 0},
	{name: "format escapes mixed with directives", script: `printf '\101%s\x42%d\n' x 7`, locale: "C", want: "AxB7\n", wantStderr: "", wantExit: 0},
	{name: "format escapes repeat per argument", script: `printf '\101%s\n' a b`, locale: "C", want: "Aa\nAb\n", wantStderr: "", wantExit: 0},
	{name: "b octal utf8 e acute", script: `printf '%b' '\303\251'`, locale: "C", want: "\xc3\xa9", wantStderr: "", wantExit: 0},
	{name: "b octal without leading zero", script: `printf '%b' '\101\7\12'`, locale: "C", want: "A\x07\n", wantStderr: "", wantExit: 0},
	{name: "b octal leading zero takes three more", script: `printf '%b' '\0101|\01234|\0'`, locale: "C", want: "A|S4|\x00", wantStderr: "", wantExit: 0},
	{name: "b octal zero overflow", script: `printf '%b' '\0400|\0777'`, locale: "C", want: "\x00|\xff", wantStderr: "", wantExit: 0},
	{name: "b hex and unicode ascii", script: `printf '%b' '\x41\x4\u0042\U00000043'`, locale: "C", want: "A\x04BC", wantStderr: "", wantExit: 0},
	{name: "b hex missing digit", script: `printf '%b' 'a\xg'`, locale: "C", want: "a\\xg", wantStderr: "bash: line 1: printf: missing hex digit for \\x\n", wantExit: 0},
	{name: "b unicode missing digit", script: `printf '%b' 'a\u'`, locale: "C", want: "a\\u", wantStderr: "bash: line 1: printf: missing unicode digit for \\u\n", wantExit: 0},
	{name: "b unicode utf8", script: `printf '%b' '\u00e9\U0001F600'`, locale: "C.UTF-8", want: "\xc3\xa9\xf0\x9f\x98\x80", wantStderr: "", wantExit: 0},
	{name: "b simple escapes", script: `printf '%b' '\a\b\e\E\f\n\r\t\v\\'`, locale: "C", want: "\x07\x08\x1b\x1b\x0c\n\x0d\t\x0b\\", wantStderr: "", wantExit: 0},
	{name: "b quotes are not escapes", script: `printf '%b' '\"\?'"'"'\'"'"''`, locale: "C", want: "\\\"\\?'\\'", wantStderr: "", wantExit: 0},
	{name: "b unknown escape", script: `printf '%b' '\q\z'`, locale: "C", want: "\\q\\z", wantStderr: "", wantExit: 0},
	{name: "b trailing backslash", script: `printf '%b' 'a\'`, locale: "C", want: "a\\", wantStderr: "", wantExit: 0},
	{name: "b stop output", script: `printf '%b|%s\n' 'a\cb' x`, locale: "C", want: "a", wantStderr: "", wantExit: 0},
	{name: "b stop output across arguments", script: `printf '%b\n' a 'b\c' c`, locale: "C", want: "a\nb", wantStderr: "", wantExit: 0},
	{name: "b width", script: `printf '[%5b][%-5b]\n' '\101' '\x42'`, locale: "C", want: "[    A][B    ]\n", wantStderr: "", wantExit: 0},
	{name: "b precision counts decoded bytes", script: `printf '[%.2b]\n' '\101\102\103'`, locale: "C", want: "[AB]\n", wantStderr: "", wantExit: 0},
	{name: "b escaped percent", script: `printf '%b\n' '100%'`, locale: "C", want: "100%\n", wantStderr: "", wantExit: 0},
	{name: "s does not decode", script: `printf '%s\n' '\101\x41'`, locale: "C", want: "\\101\\x41\n", wantStderr: "", wantExit: 0},
	{name: "q does not decode", script: `printf '%q\n' '\101'`, locale: "C", want: "\\\\101\n", wantStderr: "", wantExit: 0},
}
